export const GROUP_CHAT_LOADING = 'GROUP_CHAT_LOADING';
export const GROUP_CHAT_SUCCESS = 'GROUP_CHAT_SUCCESS';
export const GROUP_CHAT_FAILED = 'GROUP_CHAT_FAILED';

export const PERSONAL_CHAT_LOADING = 'PERSONAL_CHAT_LOADING';
export const PERSONAL_CHAT_SUCCESS = 'PERSONAL_CHAT_SUCCESS';
export const PERSONAL_CHAT_FAILED = 'PERSONAL_CHAT_FAILED';
export const SET_CTRL = 'SET_CTRL';
export const CLOSE_CHAT = 'CLOSE_CHAT';
