export const GET_EVENTS_LOADING = 'GET_EVENTS_LOADING';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED';

export const CREATE_EVENTS_LOADING = 'CREATE_EVENTS_LOADING';
export const CREATE_EVENTS_SUCCESS = 'CREATE_EVENTS_SUCCESS';
export const CREATE_EVENTS_FAILED = 'CREATE_EVENTS_FAILED';

export const GET_MY_EVENTS_LOADING = 'GET_MY_EVENTS_LOADING';
export const GET_MY_EVENTS_SUCCESS = 'GET_MY_EVENTS_SUCCESS';
export const GET_MY_EVENTS_FAILED = 'GET_MY_EVENTS_FAILED';

export const ADD_EVENT_LIKE = 'ADD_EVENT_LIKE';
