export const SET_TITLE = 'SET_TITLE';
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';

export const GET_ALL_STATUS_LOADING = 'GET_ALL_STATUS_LOADING';
export const GET_ALL_STATUS_SUCCESS = 'GET_ALL_STATUS_SUCCESS';
export const GET_ALL_STATUS_FAIL = 'GET_ALL_STATUS_FAIL';
export const DELETE_STATUS_LOADING = 'DELETE_STATUS_LOADING';
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';
export const DELETE_STATUS_FAIL = 'DELETE_STATUS_FAIL';
