export const GET_MICROBLOGS_LOADING = 'GET_MICROBLOGS_LOADING';
export const GET_MICROBLOGS_SUCCESS = 'GET_MICROBLOGS_SUCCESS';
export const GET_MICROBLOGS_FAILED = 'GET_MICROBLOGS_FAILED';

export const CREATE_MICROBLOG_LOADING = 'CREATE_MICROBLOG_LOADING';
export const CREATE_MICROBLOG_SUCCESS = 'CREATE_MICROBLOG_SUCCESS';
export const CREATE_MICROBLOG_FAILED = 'CREATE_MICROBLOG_FAILED';

export const GET_MICROBLOGS_FOR_INVITE_LOADING =
  'GET_MICROBLOGS_FOR_INVITE_LOADING';
export const GET_MICROBLOGS_FOR_INVITE_SUCCESS =
  'GET_MICROBLOGS_FOR_INVITE_SUCCESS';
export const GET_MICROBLOGS_FOR_INVITE_FAILED =
  'GET_MICROBLOGS_FOR_INVITE_FAILED';
