export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const EDIT_USER_LOADING = 'EDIT_USER_LOADING';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const DELETE_USER_LOADING = 'DELETE_USER_LOADING';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const GET_USERMETA_LOADING = 'GET_USERMETA_LOADING';
export const GET_USERMETA_SUCCESS = 'GET_USERMETA_SUCCESS';
export const GET_USERMETA_FAIL = 'GET_USERMETA_FAIL';

export const GET_FEATURE = 'GET_FEATURE';
export const GET_PROFILE = 'GET_PROFILE';
export const USER_PROFILE_CHANGE = 'USER_PROFILE_CHANGE';
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';

export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_FAIL = 'SET_PROFILE_FAIL';

export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST';
export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';
export const CANCEL_FRIEND_REQUEST = 'CANCEL_FRIEND_REQUEST';
export const LOAD_META = 'LOAD_META';

export const GET_FRIENDS_LOADING = 'GET_FRIENDS_LOADING';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_FAILED = 'GET_FRIENDS_FAILED';
